### ISSUE TITLE
Find a date for the next meeting

### ISSUE THREAD

**Issue by benjie** [graphql/client-controlled-nullability-wg#3]
We wish to meet again before the August GraphQL Primary WG, Calvin from Apollo is to organize a date via Discord, then Benjie will set up the Zoom meeting

- assignee(s): @calvincestari and @Benjie
- source: https://github.com/graphql/client-controlled-nullability-wg/blob/main/notes/2023/2023-07.md#first-meeting-july-19th

---

_Note: Action Item issues are reviewed and closed during Working Group
meetings._

**Comment by benjie** [comment]
@calvincestari Please write a response here so I can assign you :)

**Comment by calvincestari** [comment]
Yes, I'm happy to take this task on.

**Comment by calvincestari** [comment]
The first meeting will be scheduled for July 26, 2023 12:00 PM (PDT). We'll do the first one like that and can consider alternating with the earlier time for Euro timezones if needed going forward.

**Comment by calvincestari** [comment]
@benjie this issue can probably be closed now, thanks.

**Comment by benjie** [comment]
Protocol is to close them during action item review 👍
